### ISSUE TITLE
Create notification method 

### ISSUE THREAD

**Issue by verolero86** [olcf/harmony#4]
In certain scenarios harmony should send a notification to alert us of failures, or when the queue empties. Email and SMS notification is desired.

**Comment by reubendb** [comment]
For now just use `localhost` to send mail from wherever this is run from. For example, on any of login node you can something like: `cat myfile.txt | mail email@domain.com` to send email. We can change the mail server later if it becomes necessary (just make the script generic enough to make it easier to change).

**Comment by kuchtact** [comment]
Added capability in ed1339e7ff9939079a04373d7ec24f9650705bff.
