### ISSUE TITLE
LSF will terminate the job before when the walltime is hit.

### ISSUE THREAD

**Issue by verolero86** [olcf/harmony#7]
https://github.com/olcf/harmony/blob/ed1339e7ff9939079a04373d7ec24f9650705bff/scripts/job_status.py#L66

There should be a status code returned when LSF terminates the job vs. one exits successfully.

**Comment by kuchtact** [comment]
I fixed this by looking at the exit status and deciding from there. I'm not sure if all wall time exits always have the same code but I'm pretty sure that they do.
